#include "topgear_internal.h"
#include "sc_static_apu.h"
#include <stdio.h>
#include <stdlib.h>
static FILE *out;
static void record(uint64_t clock,unsigned port,uint8_t value){fprintf(out,"{%lluULL,%u,%u},\n",(unsigned long long)clock,port,(unsigned)value);}
int main(int argc,char **argv){
 FILE *f;uint8_t rom[524288];TopGearRecomp *i;char error[256];unsigned n;
 if(argc!=3)return 2;f=fopen(argv[1],"rb");if(!f)return 2;if(fread(rom,1,sizeof(rom),f)!=sizeof(rom))return 2;fclose(f);
 if(!topgear_recomp_create(&i,rom,sizeof(rom),error,sizeof(error)))return 1;
 out=fopen(argv[2],"wb");if(!out)return 2;
 fprintf(out,"/* ROM-authoritative native boot/upload port writes; regenerated by export_music_player_transcripts. */\n");
 sc_static_apu_set_cpu_port_observer(record);
 for(n=1;n<=7;n++){
  fprintf(out,"static const PortEvent song%u[]={\n",n);
  if(!topgear_recomp_music_preview_prepare(i,(uint8_t)n,error,sizeof(error))){fprintf(stderr,"%s\n",error);return 1;}
  fprintf(out,"};\n");
 }
 sc_static_apu_set_cpu_port_observer(NULL);fclose(out);topgear_recomp_destroy(i);return 0;
}
