#ifndef SC_AUDIO_CLOCK_PROFILE_H
#define SC_AUDIO_CLOCK_PROFILE_H
#include <stdint.h>

/* Measured NTSC S-SMP clock relation retained by the static audio core.
 * One S-SMP clock is generated by the exact rational accumulator below.
 * This corresponds to approximately 1,025,279.8698 S-SMP clocks/second and
 * 32,039.9959 stereo DSP frames/second against the 21,477,270 Hz S-CPU master
 * clock profile.  Real consoles have an independent ceramic resonator and can
 * differ; this profile is deterministic and is the project certification
 * profile, not a claim that every physical console has the same oscillator. */
#define SC_AUDIO_CLOCK_PROFILE_NAME "ntsc-measured-32040"
#define SC_AUDIO_CLOCK_RATIO_NUMERATOR UINT32_C(15664)
#define SC_AUDIO_CLOCK_RATIO_DENOMINATOR UINT32_C(328125)
#define SC_AUDIO_CLOCK_MASTER_HZ UINT32_C(21477270)

static inline uint64_t sc_audio_clock_advance(uint64_t master_delta,
                                              uint32_t *remainder) {
    const uint64_t whole = master_delta / SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
    const uint64_t partial = master_delta % SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
    const uint64_t numerator = partial * SC_AUDIO_CLOCK_RATIO_NUMERATOR +
                               (remainder ? *remainder : 0u);
    const uint64_t cycles = whole * SC_AUDIO_CLOCK_RATIO_NUMERATOR +
                            numerator / SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
    if (remainder)
        *remainder = (uint32_t)(numerator % SC_AUDIO_CLOCK_RATIO_DENOMINATOR);
    return cycles;
}

static inline uint32_t sc_audio_clock_remainder(uint64_t master_clock) {
    const uint64_t partial = master_clock % SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
    return (uint32_t)((partial * SC_AUDIO_CLOCK_RATIO_NUMERATOR) %
                      SC_AUDIO_CLOCK_RATIO_DENOMINATOR);
}

static inline uint64_t sc_audio_clock_closed_form(uint64_t master_clock,
                                                  uint32_t initial_remainder) {
    const uint64_t whole = master_clock / SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
    const uint64_t partial = master_clock % SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
    return whole * SC_AUDIO_CLOCK_RATIO_NUMERATOR +
           (partial * SC_AUDIO_CLOCK_RATIO_NUMERATOR + initial_remainder) /
               SC_AUDIO_CLOCK_RATIO_DENOMINATOR;
}
#endif
