#!/usr/bin/env python3
"""Emit Top Gear Version 27 fail-closed S-SMP AOT lookup and used-opcode dispatcher."""
from __future__ import annotations
import argparse,csv,hashlib,json,re
from pathlib import Path
HEADER=re.compile(r'^# schema=topgear-smp-aot-map-v27 instructions=(\d+) unique=(\d+) conflicts=(\d+) versions=(\d+) oracle=(\S+)$')
CASE=re.compile(r'(?m)^[ \t]*case[ \t]+0x([0-9a-fA-F]{2})[ \t]*:[ \t]*\{')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def matching(text,o):
 d=0;i=o;st=ch=ln=bl=False;esc=False
 while i<len(text):
  c=text[i];n=text[i+1] if i+1<len(text) else ''
  if ln:
   if c=='\n':ln=False
  elif bl:
   if c=='*' and n=='/':bl=False;i+=1
  elif st:
   if esc:esc=False
   elif c=='\\':esc=True
   elif c=='"':st=False
  elif ch:
   if esc:esc=False
   elif c=='\\':esc=True
   elif c=="'":ch=False
  else:
   if c=='/' and n=='/':ln=True;i+=1
   elif c=='/' and n=='*':bl=True;i+=1
   elif c=='"':st=True
   elif c=="'":ch=True
   elif c=='{':d+=1
   elif c=='}':
    d-=1
    if d==0:return i
  i+=1
 raise ValueError('unterminated case')
def extract(files):
 out={};hashes={}
 for p in files:
  text=p.read_text();hashes[p.name]=sha(p)
  for m in CASE.finditer(text):
   op=int(m.group(1),16);a=text.find('{',m.start());b=matching(text,a);block=text[m.start():b+1].strip()
   if op in out:raise ValueError(f'duplicate opcode {op:02X}')
   out[op]=block
 if len(out)!=256:raise ValueError(f'parsed {len(out)} opcode cases')
 return out,hashes
def route(path):
 with path.open() as f:
  h=f.readline().rstrip();m=HEADER.match(h)
  if not m:raise ValueError('bad route header')
  instructions,unique,conflicts,versions,oracle=int(m[1]),int(m[2]),int(m[3]),int(m[4]),m[5]
  r=csv.DictReader(f);rows={}
  for row in r:
   pc=int(row['pc'],16);ops=tuple(sorted({int(x,16) for x in row['opcodes'].split('|')}));rows[pc]=ops
 if conflicts or len(rows)!=unique or sum(map(len,rows.values()))!=versions:raise ValueError('route count mismatch')
 return instructions,rows,oracle
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--route',type=Path,required=True);ap.add_argument('--pseudo-dir',type=Path,required=True);ap.add_argument('--lookup',type=Path,required=True);ap.add_argument('--dispatch',type=Path,required=True);ap.add_argument('--metadata',type=Path,required=True);ap.add_argument('--code-bitmap',type=Path,required=True);ap.add_argument('--authority-seed',type=Path);ns=ap.parse_args()
 cases,hashes=extract(sorted(ns.pseudo_dir.glob('oppseudo_*.cpp')));instructions,rows,oracle=route(ns.route);used=sorted({o for v in rows.values() for o in v});bits=ns.code_bitmap.read_bytes()
 if len(bits)!=8192:raise ValueError('code bitmap must be 8192 bytes')
 lookup=['/* Generated by tools/audio/generate_static_smp_aot_v27.py. */\n','bool SMP::sc_aot_prepare(uint16 pc, uint8 actual) {\n','  uint8 expected=0xffu;\n','  switch(pc) {\n']
 for pc in sorted(rows):
  ops=rows[pc]
  if len(ops)==1:lookup.append(f'    case 0x{pc:04x}u: expected=0x{ops[0]:02x}u; break;\n')
  else:
   cond=' && '.join(f'actual != 0x{o:02x}u' for o in ops);lookup.append(f'    case 0x{pc:04x}u: if ({cond}) return sc_aot_fail(2u,pc,0xffu,actual); ++sc_aot_instructions; return true;\n')
 lookup+=['    default: return sc_aot_fail(1u,pc,0xffu,actual);\n','  }\n','  if(actual != expected) return sc_aot_fail(2u,pc,expected,actual);\n','  /* Execute the opcode selected by frozen exact-PC authority, not by the fetched byte. */\n','  opcode_number=expected;\n','  ++sc_aot_instructions; return true;\n','}\n']
 dispatch=['/* Generated used-opcode S-SMP dispatcher. No generic switch. */\n','switch(opcode_number) {\n']
 for op in used:dispatch.append(cases[op]+'\n')
 dispatch+=['default: sc_aot_fail(3u,regs.pc,0xffu,static_cast<uint8>(opcode_number)); break;\n','}\n']
 ns.lookup.write_text(''.join(lookup),newline='\n');ns.dispatch.write_text(''.join(dispatch),newline='\n')
 # C include for static code-write authority.
 bitmap_inc=ns.lookup.with_name('sc_smp_aot_code_bitmap.inc')
 lines=['/* Generated driver code-byte bitmap. */\n','static const uint8 sc_smp_aot_code_bitmap[8192] = {\n']
 for i in range(0,8192,16): lines.append('  '+','.join(f'0x{x:02x}u' for x in bits[i:i+16])+',\n')
 lines.append('};\n')
 bitmap_inc.write_text(''.join(lines),newline='\n')
 meta={'schema':'topgear-static-smp-aot-generation-v27','result':'pass','route':ns.route.name,'route_sha256':sha(ns.route),'route_oracle':oracle,'pc_opcode_contexts':sum(len(x) for x in rows.values()),'unique_pcs':len(rows),'used_opcode_count':len(used),'used_opcodes':[f'{x:02X}' for x in used],'direct_exact_pc_authority':True,'fetched_opcode_is_validation_only':True,'generic_switch_in_static_mode':False,'failure_policy':{'unknown_pc':'stop','opcode_mismatch':'stop','unemitted_opcode':'stop','code_write':'new epoch required'},'lookup_sha256':sha(ns.lookup),'dispatch_sha256':sha(ns.dispatch),'code_bitmap_sha256':sha(ns.code_bitmap),'opcode_sources':hashes}
 ns.metadata.write_text(json.dumps(meta,indent=2,sort_keys=True)+'\n',newline='\n')
 if ns.authority_seed:
  previous={}
  if ns.authority_seed.exists():previous=json.loads(ns.authority_seed.read_text())
  trace_sources=previous.get('trace_sources',[])
  project=ns.authority_seed.resolve().parents[3]
  wanted=[
   ('gap_repair_rom_derived','docs/generated/V27-SMP-GAP-REPAIR.json','ROM/initial-ARAM-derived static authority repair receipt'),
   ('command_table_cfg_closure','docs/generated/V27-SMP-COMMAND-CLOSURE.json','ROM/initial-ARAM-derived complete $01-$1D command CFG receipt'),
  ]
  by_name={row.get('name'):row for row in trace_sources}
  for name,relative,role in wanted:
   path=project/relative
   if path.exists():by_name[name]={'name':name,'path':relative,'role':role,'bytes':path.stat().st_size,'sha256':sha(path)}
  ordered=[row for row in trace_sources if row.get('name') not in {name for name,_,_ in wanted}]
  ordered.extend(by_name[name] for name,_,_ in wanted if name in by_name)
  seed={'schema':'topgear-v27-smp-authority-seed-v3','pc_opcode_contexts':meta['pc_opcode_contexts'],'unique_pcs':meta['unique_pcs'],'used_opcode_count':meta['used_opcode_count'],'used_opcodes':meta['used_opcodes'],'code_bytes':sum(byte.bit_count() for byte in bits),'production_fallback':False,'route_sha256':meta['route_sha256'],'bitmap_sha256':meta['code_bitmap_sha256'],'lookup_sha256':meta['lookup_sha256'],'dispatch_sha256':meta['dispatch_sha256'],'coverage_note':f'{meta["unique_pcs"]} exact S-SMP PCs freeze certified routes and the complete ROM-derived $01-$1D command CFG. Unknown PCs/opcode mismatches/code writes still fail closed in production.','trace_sources':ordered}
  ns.authority_seed.write_text(json.dumps(seed,indent=2,sort_keys=True)+'\n',newline='\n')
 print(json.dumps(meta,indent=2))
if __name__=='__main__':
 try:main()
 except ValueError as e:raise SystemExit(str(e))
